
ekf_node:
  ros__parameters:
    use_sim_time: true
    imu_topic: /livox/imu
    nominal_dt: 0.005
    use_stamp_dt: true
    predict_use_linear_accel: true
    imu_stamp_offset_sec: 0.0
    lidar_stamp_offset_sec: 0.0
    max_odom_tf_publish_rate_hz: 25.0

    odom_frame: odom
    base_link_frame: base_link
    publish_tf: true
    transform_imu_to_base_link: true
    imu_tf_lookup_timeout_sec: 0.05
    imu_source_topic: /ekf/imu_source
    imu_source_id: livox

    process_noise_diag:
      - 3.0e-4
      - 3.0e-4
      - 1.0e-6
      - 2.0e-6
      - 7.0e-3
      - 7.0e-3
      - 1.0e-8
      - 1.0e-8
      - 1.0e-10

    initial_cov_diag:
      - 0.5
      - 0.5
      - 0.5
      - 0.5
      - 0.5
      - 0.5
      - 0.01
      - 0.01
      - 1.0e-4

    flat_orientation_variance: 1.0e-4

    publish_topic: /ekf/odom
    pose_topic: /ekf/pose
    path_topic: /ekf/path

    lidar_odom_topic: "/lidar/odom"
    lidar_delta_topic: ""
    lidar_delta_vel_var: 0.22
    lidar_delta_gate_nis: 200.0
    lidar_delta_nominal_dt_sec: 0.1
    lidar_pose_topic: ""
    lidar_z_topic: ""

    lidar_pose_var: 0.015
    lidar_yaw_var: 0.008
    lidar_z_var: 0.05
    lidar_require_frames: true
    lidar_fuse_z_from_odom: false
    lidar_gate_nis: 32.0
    lidar_use_roll_pitch: false
