
port: "/dev/ttyACM0"
baudrate: 115200

frame_id: "imu_link"
imu_frame_id: "imu_link"
mount_frame_id: "base_link"

publish_mount_to_frame_id_transform: false

mount_to_frame_id_transform: [0.0, 0.0, 0.065, 0.0, 0.0, -0.7071067811865475, 0.7071067811865476]

imu_data_raw_rate: 200
imu_data_rate: 0
